#!/bin/bash

NUMBER1=200
NUMBER2=300

SUM=$(($NUMBER1 + $NUMBER2))
echo "The sum of $NUMBER1 and $NUMBER2 is: $SUM"

LEADERS=("Trump" "Putin" "Modi" "Biden" "Xi")
echo "World Leaders: ${LEADERS[@]}"
echo "Number of Leaders: ${#LEADERS[@]}"
echo "First Leader: ${LEADERS[0]}"