#!/bin/bash
PERSON1=John
PERSON2=RAHEEM
echo "$PERSON1:: hi $PERSON2, how are you?"
echo "$PERSON2:: hi $PERSON1, I am fine. how about you?"
echo "$PERSON1:: I am also fine. what are you doing thesedays?"
echo "$PERSON2:: I am learning bash scripting. it's fun!"